# https://github.com/alexta69/metube
version: '3'
services:
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    restart: unless-stopped
    ports:
      - "8888:8081"
    volumes:
      - $HOME/Downloads/metube-downloads:/downloads
